import { useState } from "react";
import { useLocation } from "wouter";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { ArrowLeft, Brain, Target, List } from "lucide-react";
import DiagnosticChecklist from "@/components/DiagnosticChecklist";
import DomainSelector from "@/components/DomainSelector";

export default function DiagnosticPage() {
  const [, setLocation] = useLocation();
  const [issue, setIssue] = useState("");
  const [selectedDomain, setSelectedDomain] = useState<string | null>(null);
  const [showChecklist, setShowChecklist] = useState(false);

  const handleGenerateChecklist = () => {
    if (issue.trim()) {
      setShowChecklist(true);
    }
  };

  const handleChecklistComplete = () => {
    // When checklist is complete, offer support options
    setLocation('/live-support');
  };

  return (
    <div className="container mx-auto p-4 max-w-4xl">
      <div className="flex items-center gap-2 mb-6">
        <Button variant="ghost" size="sm" onClick={() => setLocation('/')}>
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back to Home
        </Button>
        <div className="flex items-center gap-2">
          <Target className="h-6 w-6 text-blue-600" />
          <h1 className="text-2xl font-bold">AI Diagnostic Checklist</h1>
        </div>
      </div>

      {!showChecklist ? (
        <div className="space-y-6">
          {/* Introduction */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Brain className="h-5 w-5 text-blue-600" />
                Get a Personalized Troubleshooting Checklist
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-600 mb-4">
                Our AI will analyze your technical issue and create a customized step-by-step diagnostic checklist. 
                Follow the systematic approach to identify and resolve your problem efficiently.
              </p>
              
              <div className="grid md:grid-cols-3 gap-4 mb-6">
                <div className="p-4 bg-blue-50 rounded-lg">
                  <List className="h-6 w-6 text-blue-600 mb-2" />
                  <h3 className="font-medium text-blue-900">Systematic Approach</h3>
                  <p className="text-sm text-blue-700">Progressive steps from simple to advanced diagnostics</p>
                </div>
                <div className="p-4 bg-green-50 rounded-lg">
                  <Target className="h-6 w-6 text-green-600 mb-2" />
                  <h3 className="font-medium text-green-900">Personalized</h3>
                  <p className="text-sm text-green-700">Tailored to your specific issue and technical level</p>
                </div>
                <div className="p-4 bg-purple-50 rounded-lg">
                  <Brain className="h-6 w-6 text-purple-600 mb-2" />
                  <h3 className="font-medium text-purple-900">AI-Powered</h3>
                  <p className="text-sm text-purple-700">Generated by advanced AI diagnostic algorithms</p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Issue Input Form */}
          <Card>
            <CardHeader>
              <CardTitle>Describe Your Technical Issue</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Issue Category (Optional)
                </label>
                <DomainSelector 
                  selectedDomain={selectedDomain}
                  onDomainChange={setSelectedDomain}
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Describe your issue in detail *
                </label>
                <Textarea
                  placeholder="Please provide as much detail as possible about your technical issue. Include:&#10;• What device/software you're using&#10;• When the problem started&#10;• What you were doing when it occurred&#10;• Any error messages you've seen&#10;• What you've already tried&#10;&#10;Example: 'My Windows 10 laptop has been running very slowly for the past week. It takes 5+ minutes to boot up and programs freeze frequently. I've noticed the fan running loudly and the laptop feels hot. I haven't installed any new software recently.'"
                  value={issue}
                  onChange={(e) => setIssue(e.target.value)}
                  rows={8}
                  className="w-full"
                />
              </div>
              
              <Button 
                onClick={handleGenerateChecklist}
                disabled={!issue.trim()}
                className="w-full"
                size="lg"
              >
                <Brain className="h-4 w-4 mr-2" />
                Generate AI Diagnostic Checklist
              </Button>
            </CardContent>
          </Card>
        </div>
      ) : (
        <DiagnosticChecklist 
          issue={issue}
          category={selectedDomain || undefined}
          onComplete={handleChecklistComplete}
        />
      )}
    </div>
  );
}